name: Update repository for GIN datasets

on:
  schedule:
    - cron: '0 12 * * 6'  # Only run on Saturday
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '^3.11'

      - name: Set up environment
        run: |
          git config --global user.email "test@github.land"
          git config --global user.name "GitHub Almighty"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade tox

      - name: Run script
        # No space between `-e` and `run` or tox gets confused
        run: tox -erun -- -l DEBUG --hosts GIN,hub.datalad.org,ATRIS
        env:
          GIN_TOKEN: ${{ secrets.GIN_TOKEN }}
          HUB_DATALAD_ORG_TOKEN: ${{ secrets.HUB_DATALAD_ORG_TOKEN }}

      - name: Push changes
        run: |
          ahead="$(git rev-list --count --right-only @{upstream}...HEAD)"
          if [ "$ahead" -gt 0 ]
          then git push
          else echo "No commits to push"
          fi

# vim:set et sts=2:
